Update patch set 2
Patch Set 2:

Failure might be due to missing replication on partner and keystone.

FailedGobActionException: Failed replication due to: [status: NOT_FOUND
source: "googleplex-android/platform/external/cn-cbor"
destination: "partner-android/platform/external/cn-cbor"

Patch-set: 2
Reviewer: Gerrit User 1110792 <1110792@85c56323-6fa9-3386-8a01-6480fb634889>