superproject - add contactinfo and bugurl to file bugs in manifest.
Bug: 186220520
Tested: manaul

$ repo_dev sync --use-superproject
WARNING: --use-superproject is experimental and not for general use
/usr/local/google/home/rtenneti/work/drive2/android/WORKING_DIRECTORY/.repo/exp-superproject/925043f706ba64db713e9bf3b55987e2-superproject.git: Performing initial setup for superproject; this might take several minutes.
/usr/local/google/home/rtenneti/work/drive2/android/WORKING_DIRECTORY/.repo/exp-superproject/925043f706ba64db713e9bf3b55987e2-superproject.git: Initial setup for superproject completed.
error: please file a bug using go/repo-bug to report missing commit_ids for: []

Change-Id: Ide474ccfd9eaaf82da99067bd9684ec8c56190d3
Merged-In: I1a9dfd6df5e06d1288e732e174cb863ec0ff3081
(cherry picked from commit f1f67885e2d19ab0a62593090b8c8924ac465ec8)