Add system/extras and system/media to the master-art manifest.
These projects are new dependencies of the master-art
manifest:

- system/extras: This is to honor a new dependency on
libpagemap, which is part of system/extras, and address the
following build error:

  error: system/core/libmemtrack/Android.bp:19:1: "memtrack_test" depends on undefined module "libpagemap"

- system/media: This is to address the following build error:

  error: hardware/libhardware/tests/hardware/Android.bp:1:1: source path system/media/camera/include does not exist

Test: art/tools/buildbot-build.sh -j30 --host
Change-Id: I4b6d4cc69ea9ae4848182f8d771737e460364f28